### PR TITLE
Detach devices on remove

### PR DESCRIPTION
**Pull request by izquiratops**
I'm still being able to see the green dot on my iPhone after getting out of the camera screen. I think the devices are still being used once the component is unmounted.

### CODE REVIEW

**Comment by Andriiklymiuk** [comment]
what is the status of this one? why it is not merged?
I cam confirm, that this fix helps to resolve the isse

**Comment by Andriiklymiuk** [comment]
what is the status of this one?

**Comment by izquiratops** [comment]
> what is the status of this one?

I don't know, would be great to have a review since both pull requests (publish fix and this one) seems to be crucial 😞

**Comment by Andriiklymiuk** [comment]
added new [react-native-publisher](https://github.com/Andriiklymiuk/react-native-publisher) with other fixes, till this library maintainers check MRs

**Review by ezranbayantemur — APPROVED** [review]

**Comment by ezranbayantemur** [comment]
Hello @izquiratops, thanks for the contribution. Can you change the target branch to `develop` branch?

**Pull request closed without merging**
